Recipes.addShaped({id: ItemID.pipeOxygen, count: 1, data: 0}, [ "xxx", "   ", "xxx" ], ['x', 102, -1]);
Recipes.addShaped({id: BlockID.refinery, count: 1, data: 0}, [ "aaa", "dbd", "xcx"], ['a', 325, -1, 'b', BlockID.machineBlockBasic, -1, 'c', ItemID.circuitBasic, -1, 'd', ItemID.cableTin1, -1, 'x', ItemID.plateCopper, -1]);
Recipes.addShaped({id: BlockID.deconstructor, count: 1, data: 0}, [ " c ", "bab", "ddd"], ['c', 58, -1, 'a', BlockID.machineBlockBasic, -1, 'b', ItemID.circuitBasic, -1, 'd', ItemID.plateBronze, -1]);
Recipes.addShaped({id: ItemID.ventAir, count: 1, data: 0}, [ "xx", "xy"], ['x', ItemID.plateTin, -1, 'y', ItemID.plateBronze, -1]);
Recipes.addShaped({id: ItemID.fanAir, count: 1, data: 0}, [ "x x", " y ", "xzx"], ['x', ItemID.plateIron, -1, 'y', ItemID.circuitBasic, -1, 'z', 331, -1]);
Recipes.addShaped({id: ItemID.oxygen_concentrator, count: 1, data: 0}, [ "xzx", "zyz", "xax"], ['x', ItemID.plateIron, -1, 'y', ItemID.copperCanister, -1, 'z', ItemID.plateTin, -1, 'a', ItemID.ventAir, -1]);
Recipes.addShaped({id: ItemID.canvas, count: 1, data: 0}, [ " xy", "xxx", "yx "], ['x', 287, -1, 'y', 280, -1]);
Recipes.addShaped({id: ItemID.gearOxygen, count: 1, data: 0}, [ " x ", "xyx", "x x"], ['x', ItemID.pipeOxygen, -1, 'y', ItemID.oxygen_concentrator, -1]);
Recipes.addShaped({id: ItemID.maskOxygen, count: 1, data: 0}, [ "xyx", "x x", "x x"], ['x', 20, -1, 'y', 306, -1]);
Recipes.addShaped({id: ItemID.basicFrecuencemodule, count: 1, data: 0}, [ "zzz", "zyz", "xyx"], ['x', 331, -1, 'y', ItemID.circuitBasic, -1, 'z', ItemID.plateTin, -1]);
Recipes.addShaped({id: ItemID.oxygenbigTank, count: 1, data: 0}, [ "xxx", "yyy", "zzz"], ['x', 35, 14, 'y', ItemID.tinCanister, -1, 'z', ItemID.plateCopper, -1]);
Recipes.addShaped({id: ItemID.oxygenmedTank, count: 1, data: 0}, [ "xx ", "yy ", "zz "], ['x', 35, 1, 'y', ItemID.tinCanister, -1, 'z', ItemID.plateCopper, -1]);
Recipes.addShaped({id: ItemID.oxygensmallTank, count: 1, data: 0}, [ "x  ", "y  ", "z  "], ['x', 35, 4, 'y', ItemID.tinCanister, -1, 'z', ItemID.plateCopper, -1]);
Recipes.addShaped({id: ItemID.oxygenmedTank, count: 1, data: 0}, [ " xx", " yy", " zz"], ['x', 35, 1, 'y', ItemID.tinCanister, -1, 'z', ItemID.plateCopper, -1]);
Recipes.addShaped({id: ItemID.oxygensmallTank, count: 1, data: 0}, [ " x ", " y ", " z "], ['x', 35, 4, 'y', ItemID.tinCanister, -1, 'z', ItemID.plateCopper, -1]);
Recipes.addShaped({id: ItemID.oxygensmallTank, count: 1, data: 0}, [ "  x", "  y", "  z"], ['x', 35, 4, 'y', ItemID.tinCanister, -1, 'z', ItemID.plateCopper, -1]);
Recipes.addShaped({id: ItemID.engine, count: 1, data: 0}, [ " a ", "xyx", "xzx"], ['x', ItemID.dutyHeavy1, 4, 'y', ItemID.circuitBasic, -1, 'z', ItemID.ventAir, -1, 'a', 259, -1]);
Recipes.addShaped({id: ItemID.noseCone, count: 1, data: 0}, [ " y ", " x ", "x x"], ['x', ItemID.dutyHeavy1, 4, 'y', ItemID.circuitBasic, -1]);
Recipes.addShaped({id: ItemID.finsRocket, count: 1, data: 0}, [ " y ", "xyx", "x x"], ['x', ItemID.dutyHeavy1, 4, 'y', ItemID.plateSilicon, -1]);
Recipes.addShaped({id: ItemID.plainParachute, count: 1, data: 0}, [ "yyy", "x x", " x "], ['x', 287, 4, 'y', ItemID.canvas, -1]);
Recipes.addShaped({id: ItemID.blueParachute, count: 1, data: 0}, [ "x", "y"], ['x', 351, 12, 'y', ItemID.plainParachute, -1]);
Recipes.addShaped({id: ItemID.darkblueParachute, count: 1, data: 0}, [ "x", "y"], ['x', 351, 4, 'y', ItemID.plainParachute, -1]);
//Recipes.addShaped({id: ItemID.limeParachute, count: 1, data: 0}, [ "x", "y"], ['x', 351, 10, 'y', ItemID.plainParachute, -1]);
//Recipes.addShaped({id: ItemID.blackParachute, count: 1, data: 0}, [ "x", "y"], ['x', 351, 0, 'y', ItemID.plainParachute, -1]);
//Recipes.addShaped({id: ItemID.magentaParachute, count: 1, data: 0}, [ "x", "y"], ['x', 351, 13, 'y', ItemID.plainParachute, -1]);
//Recipes.addShaped({id: ItemID.orangeParachute, count: 1, data: 0}, [ "x", "y"], ['x', 351, 14, 'y', ItemID.plainParachute, -1]);
//Recipes.addShaped({id: ItemID.redParachute, count: 1, data: 0}, [ "x", "y"], ['x', 351, 1, 'y', ItemID.plainParachute, -1]);
//Recipes.addShaped({id: ItemID.yelowParachute, count: 1, data: 0}, [ "x", "y"], ['x', 351, 11, 'y', ItemID.plainParachute, -1]);
//Recipes.addShaped({id: ItemID.grayParachute, count: 1, data: 0}, [ "x", "y"], ['x', 351, 7, 'y', ItemID.plainParachute, -1]);
//Recipes.addShaped({id: ItemID.tealParachute, count: 1, data: 0}, [ "x", "y"], ['x', 351, 12, 'y', ItemID.plainParachute, -1]);
//Recipes.addShaped({id: ItemID.brownParachute, count: 1, data: 0}, [ "x", "y"], ['x', 351, 3, 'y', ItemID.plainParachute, -1]);
//Recipes.addShaped({id: ItemID.darkgreenParachute, count: 1, data: 0}, [ "x", "y"], ['x', 351, 2, 'y', ItemID.plainParachute, -1]);
//Recipes.addShaped({id: ItemID.pinkParachute, count: 1, data: 0}, [ "x", "y"], ['x', 351, 9, 'y', ItemID.plainParachute, -1]);
//Recipes.addShaped({id: ItemID.purpleParachute, count: 1, data: 0}, [ "x", "y"], ['x', 351, 5, 'y', ItemID.plainParachute, -1]);
Recipes.addShaped({id: BlockID.collectorOxygen, count: 1, data: 0}, [ "cyc", "axb", "fzf"], ['x', BlockID.machineBlockBasic, -1, 'y', ItemID.circuitBasic, -1, 'z', ItemID.oxygen_concentrator, -1, 'a', ItemID.ventAir, -1, 'b', ItemID.fanAir, -1, 'c', ItemID.plateIron, -1, 'f', ItemID.plateTin, -1]);
Recipes.addShaped({id: BlockID.compressorOxygen, count: 1, data: 0}, [ "yyy", "zxz", "aaa"], ['x', BlockID.machineBlockBasic, -1, 'y', ItemID.circuitBasic, -1, 'z', ItemID.oxygen_concentrator, -1, 'a', ItemID.plateLead, -1,]);
Recipes.addShaped({id: ItemID.dutyHeavy1, count: 1, data: 0}, [ "xyz"], ['x', ItemID.plateSteel, -1, 'y', ItemID.plateBronze, -1, 'z', ItemID.plateSilicon, -1]);
