//декоративные блоки
IDRegistry.genBlockID("glassTin");
Block.createBlock("glassTin", [{name: "Tin glass", texture: [["glassTin", 1]], inCreative: true}]);
IDRegistry.genBlockID("glassClear");
Block.createBlock("glassClear", [{name: "Clear glass", texture: [["glassClear", 1]], inCreative: true}]);
IDRegistry.genBlockID("glassSapphire");
Block.createBlock("glassSapphire", [{name: "Sapphire glass", texture: [["glassSapphire", 1]], inCreative: true}]);
IDRegistry.genBlockID("decoTin");
Block.createBlock("decoTin", [{name: "Decor tin block", texture: [["decoTin", 1]], inCreative: true}]);
IDRegistry.genBlockID("station");
Block.createBlock("station", [{name: "Station", texture: [["topStation", 1], ["sideStation", 1]], inCreative: true}]);
IDRegistry.genBlockID("oil");
Block.createBlock("oil", [{name: "Oil", texture: [["Oil", 1]], inCreative: true}]);
IDRegistry.genBlockID("oreCheese");
Block.createBlock("oreCheese", [{name: "Cheese ore", texture: [["oreCheese", 1]], inCreative: true}]);
IDRegistry.genBlockID("oreSapphire");
Block.createBlock("oreSapphire", [{name: "Sapphire ore", texture: [["oreSapphire", 1]], inCreative: true}]);
IDRegistry.genBlockID("oreTinm");
Block.createBlock("oreTinm", [{name: "Moon Tin ore", texture: [["oreTinm", 1]], inCreative: true}]);
IDRegistry.genBlockID("oreCopperm");
Block.createBlock("oreCopperm", [{name: "Moon Copper ore", texture: [["oreCopperm", 1]], inCreative: true}]);
