IDRegistry.genItemID("ventAir"); 
Item.createItem("ventAir", "ventAir", {name: "ventAir", meta: 1}, {});
IDRegistry.genItemID("fanAir"); 
Item.createItem("fanAir", "Air fan", {name: "fanAir", meta: 1}, {});
IDRegistry.genItemID("oxygen_concentrator"); 
Item.createItem("oxygen_concentrator", "Oxygen concentrator", {name: "oxygen_concentrator", meta: 1}, {});
IDRegistry.genItemID("canvas"); 
Item.createItem("canvas", "Canvas", {name: "canvas", meta: 1}, {});
IDRegistry.genItemID("poleSteel"); 
Item.createItem("poleSteel", "Steel pole", {name: "poleSteel", meta: 1}, {});
IDRegistry.genItemID("pipeOxygen"); 
Item.createItem("pipeOxygen", "Oxygen pipe", {name: "pipeOxygen", meta: 1}, {});
